name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: 3.13
        cache: pip

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Build
      run: python build.py -c ws63-liteos-app

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ws63-liteos-app_all.fwpkg
        path: ./output/ws63/fwpkg/ws63-liteos-app/ws63-liteos-app_all.fwpkg
