name: Update Submodules
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0:00执行

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Update Submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
        
      - name: Commit update
        run: |
          git config --global user.name 'wellwhz'
          git config --global user.email 'wellwhz@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "feat: 自动更新子模块" && git push || echo "No changes to commit"        
